server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTELSERVICE
  config:
    import: optional:configserver:http://localhost:8085

     # Images Realated Configration



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-40316538.okta.com/oauth2/default
    audience: api://default

